[QMX]
# model : can be Low, Mid, High, Plus
model = Plus

[Serial]
# please adopt to your situation
port = COM7

[Messages]
# callsign is also used for RBN search and DX Cluster login
callsign = NOCALL

# button 1 : whatever you want with own text on the button
message_1 = R UR 55N 55N OP JOHAN 73
literal_1 = REPORT

# button 2 : whatever you want with own text on the button
message_2 = TU
literal_2 = TU

# CQ message : free to program but you can reuse given callsign with ${Messages:callsign}
cq = CQ CQ CQ DE ${Messages:callsign} ${Messages:callsign} ${Messages:callsign} K

[Memories]
# frequency in kHz, Mode
# fixed to 12 buttons exactly!!
fixed = 3630,LSB;
        7073,LSB;
        14060,CW;
        14292,USB

# variable number of memories shown in the drop down
extra = 3622,LSB;
        3692,LSB;
        5351,CW;
        5450,USB;
        5505,USB;
        6622,USB;
        7060,LSB;
        11175,USB;
        13264,USB;
        14044,CW;
        14345,USB;
        27555,USB;
        28450,USB;
        50313,DIGI;
        6640,LSB;
	 6085,AM;
	 6130,AM

[ModeColors]
# just for convenience you can change 
map = 	 LSB:orange;
        USB:orange;     
        CW:#0FF40B;
        AM:violet;
        DIGI:#0B80F4

[Bandplan]
160m = 1810,1838,CW;
       1840,2000,LSB
80m  = 3500,3570,CW;
       3600,3800,LSB
60m  = 5350,5354,CW;
       5354,5365,USB
40m  = 7000,7050,CW;
       7050,7200,LSB
30m  = 10100,10150,CW
20m  = 14000,14070,CW;
       14100,14350,USB
17m  = 18068,18110,CW;
       18111,18168,USB
15m  = 21000,21070,CW;
       21100,21450,USB
12m  = 24890,24930,CW;
       24931,24990,USB
11m  = 27000,28000,USB
10m  = 28000,28070,CW;
       28100,29700,USB
6m   = 50000,51000,CW;
       50100,53500,USB

[DXCluster]
servers =
    	dxc.pi4cc.nl,8000
    	dxcluster.iu1bow.it,7300
    	dx1.g5gdx.com,7300
    	dxc.hamserve.uk,7300

call = ${Messages:callsign}

[DXFilters]
commands = 
    clear/spots all
    accept/spots on hf and by_zone 14,15,16


[RBNetwork]
host = telnet.reversebeacon.net
port = 7000


[Spots]
bands = 15,20,40
modes = CW,SSB
max_age = 15
europe = True


[Cloudlog]
URL = https://Your Cloudlog Root URL/
APIKey = Your API Key
StationID = 1
